### PR TITLE
Add Report Listing to admin bar menu

### PR DESCRIPTION
**Pull request by kcristiano**
Update admin_bar_add to have a menu item for Reports

### CODE REVIEW

**Comment by christianwach** [comment]
@kcristiano Thanks for the PR! Could you convert to tab-indented whitespace please?

**Comment by christianwach** [comment]
I think this also needs a check for the CiviReport component being active - basically the same format as the other menu items: `if ( array_key_exists( 'CiviReport', $components ) ) { ...` since CiviReport can be switched off.

One last thing to check - I had problems when checking permissions with the `access_civireport` format - hence my use of the `access CiviReport` format throughout the menu method. Could you please double-check? Thanks!

**Comment by kcristiano** [comment]
@christianwach I never disable CiviReports, so it did not occur to me to add the check, thanks for pointing it out.

Both formats of permission checks work for me in Single Site.  I went with `Access CiviReport` to be consistent.

I changed the code formatting from CiviCRM to WP.   I _think_ it's now correct.

**Comment by christianwach** [comment]
@kcristiano I think that's an algorithm for formatting whitespace in CiviCRM :-) Not to worry - thanks for including the checks - I'll convert to WordPress whitespace. Cheers!

**Comment by christianwach** [comment]
FWIW, done in 2c171567a664cd86df680b2cf5626e48af2d9533

**Pull request merged**
